#!/bin/bash
# App Icon Generation Script for GoldenYolk Poultry Pro

echo "=========================================="
echo "GoldenYolk - App Icon Setup Instructions"
echo "=========================================="
echo ""
echo "To generate app icons for your Flutter app, follow these steps:"
echo ""
echo "1. Create or prepare your app icon as PNG:"
echo "   - Minimum size: 1024x1024 pixels"
echo "   - Maximum size: 2048x2048 pixels (recommended)"
echo "   - Format: PNG with transparency"
echo "   - Place it at: assets/images/app_icon.png"
echo ""
echo "2. Option A: Using flutter_launcher_icons (Automatic)"
echo "   Run: flutter pub get"
echo "   Then: flutter pub run flutter_launcher_icons"
echo ""
echo "3. Option B: Using AppIcon.co (Online Tool)"
echo "   Visit: https://appicon.co/"
echo "   - Upload your 1024x1024 PNG icon"
echo "   - Download all generated files"
echo "   - Extract and place in appropriate folders"
echo ""
echo "4. For iOS (Manual):"
echo "   - Place icons in: ios/Runner/Assets.xcassets/AppIcon.appiconset/"
echo ""
echo "5. For Android (Manual):"
echo "   - Place icons in: android/app/src/main/res/mipmap-*"
echo ""
echo "=========================================="
echo "Icon Recommendations for Poultry Pro:"
echo "=========================================="
echo ""
echo "Design Tips:"
echo "- Background color: #2E7D32 (Primary Green)"
echo "- Accent color: #FFC107 (Golden Yellow)"
echo "- Use egg or rooster silhouettes for recognition"
echo "- Ensure it's clear when scaled down to small sizes"
echo ""
echo "For best results:"
echo "- Use a design tool like Figma, Adobe XD, or Affinity Designer"
echo "- Create your icon with safe margins (padding)"
echo "- Test the icon at all sizes (16px, 48px, 128px, etc.)"
echo ""
